name: Update DuckDB

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust as needed)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r weather-pipeline/requirements.txt
      
      - name: Add API Key from Secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "API_KEY=$API_KEY" >> $GITHUB_ENV

      - name: Run Python Script
        run: |
          python3 -m pip install -r weather-pipeline/requirements.txt
          python3 weather-pipeline/src/main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add weather.duckdb
          git commit -m "Updated DuckDB file"
          git push
